In [11]:
#Dependencies
import csv
import pandas as pd

In [12]:
#Find the files to clean
csvfileone="Resources/hawaii_measurements.csv"
csvfiletwo="Resources/hawaii_stations.csv"

In [13]:
#create dataframes for the files
measurements_df=pd.read_csv(csvfileone, dtype=object)
stations_df=pd.read_csv(csvfiletwo, dtype=object)

In [14]:
#view first file
measurements_df

           station        date  prcp tobs
0      USC00519397  2010-01-01  0.08   65
1      USC00519397  2010-01-02     0   63
2      USC00519397  2010-01-03     0   74
3      USC00519397  2010-01-04     0   76
4      USC00519397  2010-01-06   NaN   73
5      USC00519397  2010-01-07  0.06   70
6      USC00519397  2010-01-08     0   64
7      USC00519397  2010-01-09     0   68
8      USC00519397  2010-01-10     0   73
9      USC00519397  2010-01-11  0.01   64
10     USC00519397  2010-01-12     0   61
11     USC00519397  2010-01-14     0   66
12     USC00519397  2010-01-15     0   65
13     USC00519397  2010-01-16     0   68
14     USC00519397  2010-01-17     0   64
15     USC00519397  2010-01-18     0   72
16     USC00519397  2010-01-19     0   66
17     USC00519397  2010-01-20     0   66
18     USC00519397  2010-01-21     0   69
19     USC00519397  2010-01-22     0   67
20     USC00519397  2010-01-23     0   67
21     USC00519397  2010-01-24  0.01   71
22     USC00519397  2010-01-25     0   67
23     USC00519397  2010-01-26  0.04   76
24     USC00519397  2010-01-27  0.12   68
25     USC00519397  2010-01-28     0   72
26     USC00519397  2010-01-30   NaN   70
27     USC00519397  2010-01-31  0.03   67
28     USC00519397  2010-02-01  0.01   66
29     USC00519397  2010-02-03   NaN   67
...            ...         ...   ...  ...
19520  USC00516128  2017-07-24  0.84   77
19521  USC00516128  2017-07-25   0.3   79
19522  USC00516128  2017-07-26   0.3   73
19523  USC00516128  2017-07-27     0   75
19524  USC00516128  2017-07-28   0.4   73
19525  USC00516128  2017-07-29   0.3   77
19526  USC00516128  2017-07-30   0.3   79
19527  USC00516128  2017-07-31     0   74
19528  USC00516128  2017-08-01   NaN   72
19529  USC00516128  2017-08-02  0.25   80
19530  USC00516128  2017-08-03  0.06   76
19531  USC00516128  2017-08-05   NaN   77
19532  USC00516128  2017-08-06   NaN   79
19533  USC00516128  2017-08-07  0.05   78
19534  USC00516128  2017-08-08  0.34   74
19535  USC00516128  2017-08-09  0.15   71
19536  USC00516128  2017-08-10  0.07   75
19537  USC00516128  2017-08-11   NaN   72
19538  USC00516128  2017-08-12  0.14   74
19539  USC00516128  2017-08-13   NaN   80
19540  USC00516128  2017-08-14  0.22   79
19541  USC00516128  2017-08-15  0.42   70
19542  USC00516128  2017-08-16  0.42   71
19543  USC00516128  2017-08-17  0.13   72
19544  USC00516128  2017-08-18   NaN   76
19545  USC00516128  2017-08-19  0.09   71
19546  USC00516128  2017-08-20   NaN   78
19547  USC00516128  2017-08-21  0.56   76
19548  USC00516128  2017-08-22   0.5   76
19549  USC00516128  2017-08-23  0.45   76

[19550 rows x 4 columns]

In [15]:
#drop the rows that have missing values
measurements_clean_df=measurements_df.dropna(axis=0)

In [16]:
measurements_clean_df.reset_index()

       index      station        date  prcp tobs
0          0  USC00519397  2010-01-01  0.08   65
1          1  USC00519397  2010-01-02     0   63
2          2  USC00519397  2010-01-03     0   74
3          3  USC00519397  2010-01-04     0   76
4          5  USC00519397  2010-01-07  0.06   70
5          6  USC00519397  2010-01-08     0   64
6          7  USC00519397  2010-01-09     0   68
7          8  USC00519397  2010-01-10     0   73
8          9  USC00519397  2010-01-11  0.01   64
9         10  USC00519397  2010-01-12     0   61
10        11  USC00519397  2010-01-14     0   66
11        12  USC00519397  2010-01-15     0   65
12        13  USC00519397  2010-01-16     0   68
13        14  USC00519397  2010-01-17     0   64
14        15  USC00519397  2010-01-18     0   72
15        16  USC00519397  2010-01-19     0   66
16        17  USC00519397  2010-01-20     0   66
17        18  USC00519397  2010-01-21     0   69
18        19  USC00519397  2010-01-22     0   67
19        20  USC00519397  2010-01-23     0   67
20        21  USC00519397  2010-01-24  0.01   71
21        22  USC00519397  2010-01-25     0   67
22        23  USC00519397  2010-01-26  0.04   76
23        24  USC00519397  2010-01-27  0.12   68
24        25  USC00519397  2010-01-28     0   72
25        27  USC00519397  2010-01-31  0.03   67
26        28  USC00519397  2010-02-01  0.01   66
27        30  USC00519397  2010-02-04  0.01   69
28        31  USC00519397  2010-02-05     0   67
29        32  USC00519397  2010-02-06     0   67
...      ...          ...         ...   ...  ...
18073  19513  USC00516128  2017-07-17  0.39   72
18074  19514  USC00516128  2017-07-18   2.4   77
18075  19515  USC00516128  2017-07-19  0.27   74
18076  19516  USC00516128  2017-07-20   0.7   75
18077  19517  USC00516128  2017-07-21   0.1   72
18078  19518  USC00516128  2017-07-22     4   72
18079  19519  USC00516128  2017-07-23   0.8   78
18080  19520  USC00516128  2017-07-24  0.84   77
18081  19521  USC00516128  2017-07-25   0.3   79
18082  19522  USC00516128  2017-07-26   0.3   73
18083  19523  USC00516128  2017-07-27     0   75
18084  19524  USC00516128  2017-07-28   0.4   73
18085  19525  USC00516128  2017-07-29   0.3   77
18086  19526  USC00516128  2017-07-30   0.3   79
18087  19527  USC00516128  2017-07-31     0   74
18088  19529  USC00516128  2017-08-02  0.25   80
18089  19530  USC00516128  2017-08-03  0.06   76
18090  19533  USC00516128  2017-08-07  0.05   78
18091  19534  USC00516128  2017-08-08  0.34   74
18092  19535  USC00516128  2017-08-09  0.15   71
18093  19536  USC00516128  2017-08-10  0.07   75
18094  19538  USC00516128  2017-08-12  0.14   74
18095  19540  USC00516128  2017-08-14  0.22   79
18096  19541  USC00516128  2017-08-15  0.42   70
18097  19542  USC00516128  2017-08-16  0.42   71
18098  19543  USC00516128  2017-08-17  0.13   72
18099  19545  USC00516128  2017-08-19  0.09   71
18100  19547  USC00516128  2017-08-21  0.56   76
18101  19548  USC00516128  2017-08-22   0.5   76
18102  19549  USC00516128  2017-08-23  0.45   76

[18103 rows x 5 columns]

In [17]:
#view cleaned dataframe
measurements_clean_df.reset_index().drop(['index'],axis=1)

           station        date  prcp tobs
0      USC00519397  2010-01-01  0.08   65
1      USC00519397  2010-01-02     0   63
2      USC00519397  2010-01-03     0   74
3      USC00519397  2010-01-04     0   76
4      USC00519397  2010-01-07  0.06   70
5      USC00519397  2010-01-08     0   64
6      USC00519397  2010-01-09     0   68
7      USC00519397  2010-01-10     0   73
8      USC00519397  2010-01-11  0.01   64
9      USC00519397  2010-01-12     0   61
10     USC00519397  2010-01-14     0   66
11     USC00519397  2010-01-15     0   65
12     USC00519397  2010-01-16     0   68
13     USC00519397  2010-01-17     0   64
14     USC00519397  2010-01-18     0   72
15     USC00519397  2010-01-19     0   66
16     USC00519397  2010-01-20     0   66
17     USC00519397  2010-01-21     0   69
18     USC00519397  2010-01-22     0   67
19     USC00519397  2010-01-23     0   67
20     USC00519397  2010-01-24  0.01   71
21     USC00519397  2010-01-25     0   67
22     USC00519397  2010-01-26  0.04   76
23     USC00519397  2010-01-27  0.12   68
24     USC00519397  2010-01-28     0   72
25     USC00519397  2010-01-31  0.03   67
26     USC00519397  2010-02-01  0.01   66
27     USC00519397  2010-02-04  0.01   69
28     USC00519397  2010-02-05     0   67
29     USC00519397  2010-02-06     0   67
...            ...         ...   ...  ...
18073  USC00516128  2017-07-17  0.39   72
18074  USC00516128  2017-07-18   2.4   77
18075  USC00516128  2017-07-19  0.27   74
18076  USC00516128  2017-07-20   0.7   75
18077  USC00516128  2017-07-21   0.1   72
18078  USC00516128  2017-07-22     4   72
18079  USC00516128  2017-07-23   0.8   78
18080  USC00516128  2017-07-24  0.84   77
18081  USC00516128  2017-07-25   0.3   79
18082  USC00516128  2017-07-26   0.3   73
18083  USC00516128  2017-07-27     0   75
18084  USC00516128  2017-07-28   0.4   73
18085  USC00516128  2017-07-29   0.3   77
18086  USC00516128  2017-07-30   0.3   79
18087  USC00516128  2017-07-31     0   74
18088  USC00516128  2017-08-02  0.25   80
18089  USC00516128  2017-08-03  0.06   76
18090  USC00516128  2017-08-07  0.05   78
18091  USC00516128  2017-08-08  0.34   74
18092  USC00516128  2017-08-09  0.15   71
18093  USC00516128  2017-08-10  0.07   75
18094  USC00516128  2017-08-12  0.14   74
18095  USC00516128  2017-08-14  0.22   79
18096  USC00516128  2017-08-15  0.42   70
18097  USC00516128  2017-08-16  0.42   71
18098  USC00516128  2017-08-17  0.13   72
18099  USC00516128  2017-08-19  0.09   71
18100  USC00516128  2017-08-21  0.56   76
18101  USC00516128  2017-08-22   0.5   76
18102  USC00516128  2017-08-23  0.45   76

[18103 rows x 4 columns]

In [18]:
#view dataframe
stations_df

,station,name,latitude,longitude,elevation
0,USC00519397,"WAIKIKI 717.2, HI US",21.2716,-157.8168,3
1,USC00513117,"KANEOHE 838.1, HI US",21.4234,-157.8015,14.6
2,USC00514830,"KUALOA RANCH HEADQUARTERS 886.9, HI US",21.5213,-157.8374,7
3,USC00517948,"PEARL CITY, HI US",21.3934,-157.9751,11.9
4,USC00518838,"UPPER WAHIAWA 874.3, HI US",21.4992,-158.0111,306.6
5,USC00519523,"WAIMANALO EXPERIMENTAL FARM, HI US",21.33556,-157.71139,19.5
6,USC00519281,"WAIHEE 837.5, HI US",21.45167,-157.84889,32.9
7,USC00511918,"HONOLULU OBSERVATORY 702.2, HI US",21.3152,-157.9992,0.9
8,USC00516128,"MANOA LYON ARBO 785.2, HI US",21.3331,-157.8025,152.4

In [19]:
#make new file for cleaned df for measurements
cleaned_data_measurements="Resources/clean_measurements_hawaii.csv"
measurements_clean_df.to_csv(cleaned_data_measurements, index=False)

In [20]:
#I know stations didn't have any missing values, I just did this anyway
cleaned_station_data="Resources/clean_stations_hawaii.csv"
stations_df.to_csv(cleaned_station_data, index=False)